### ISSUE TITLE
The screenshot inplementation is buggy

### ISSUE THREAD

**Issue by kertase** [3d4pi/freepano#2]
When trying to make a shot with the little icon at the top during the selection of the area, pictures are taken permanently.

I would expect it to only make a picture once the area chosen.

Also when choosing the area the image gets moved around, thought I think it probably should not.

tested in firefox 47 and chromium 52.0.2743.82 in linux

**Comment by bugdanov** [comment]
It does not sounds like a bug, it was implemented that way.

The picture is not taken before you hit `<enter>`.

You can hit `<esc>` or click outside of the selection to cancel the capture.

**Comment by kertase** [comment]
Sorry if you misunderstood me pictures get taken at least 20 times before I hit enter all the time during the selection new pictures are taken.

**Comment by bugdanov** [comment]
Maybe you can help me to reproduce this behaviour or send me an url by mail

**Comment by bugdanov** [comment]
It looks like the project submodules are missing because you did not clone the repository with the --recursive option or did not tried to run `git submodule init` and `git submodule update` after cloning the repository.

You can figure it out when you see a .gitmodules file lying at the root of the repository.

Or afterwards in the firebug javascript console, or in the chromium dev tools ( `<shift>-<ctrl>-<J>`) , where you should observe the messages (or more) when something goes wrong.
